name: StudyFlow
options:
  bundleIdPrefix: com.studyflow
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    INFOPLIST_KEY_CFBundleDisplayName: "StudyFlow"

targets:
  StudyFlow:
    type: application
    platform: macOS
    sources:
      - StudyFlow
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.studyflow.app
        GENERATE_INFOPLIST_FILE: "YES"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.productivity"
        INFOPLIST_KEY_NSUserNotificationsUsageDescription: "StudyFlow sends notifications when your timer completes."
        ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
